name: Docker Swarm CI/CD

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: ${{ github.sha }}
  HARBOR_HOST: 192.168.56.200:5000
  HARBOR_USERNAME: admin
  HARBOR_PASSWORD: Harbor12345
  SERVICE_NAME: ecommerce-b_shop-web
  IMAGE_NAME: ecommerce/shop-web

jobs:
  build-push-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to Harbor
        run: |
          echo "${HARBOR_PASSWORD}" | docker login ${HARBOR_HOST} \
            -u "${HARBOR_USERNAME}" \
            --password-stdin

      - name: Build shop-web image
        run: |
          docker build -t ${HARBOR_HOST}/${IMAGE_NAME}:${IMAGE_TAG} ./app/shop-web

      - name: Push shop-web image
        run: |
          docker push ${HARBOR_HOST}/${IMAGE_NAME}:${IMAGE_TAG}

      - name: Deploy to Swarm
        run: |
          docker service update \
            --with-registry-auth \
            --image ${HARBOR_HOST}/${IMAGE_NAME}:${IMAGE_TAG} \
            ${SERVICE_NAME}
